# Generated by Django 4.1 on 2022-09-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constrains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_slot_in_day', models.IntegerField()),
                ('min_slot_in_day', models.IntegerField()),
                ('max_num_of_days', models.IntegerField()),
                ('min_num_of_days', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
