# Generated by Django 4.1 on 2022-09-03 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Constrains',
            new_name='Constrain',
        ),
    ]
